### ISSUE TITLE
Nacos 注册问题

### ISSUE THREAD

**Issue by gfrogz** [tx7do/kratos-bootstrap#2]
nacos 版本2.3.1

**Comment by lugcz** [comment]
模块：rpc
注册xxx.core.service
在nacos里的服务器名为： xxx.core.service.grpc
rpc.CreateGrpcClient会导致 `log.Fatalf("dial grpc client [%s] failed: %s", serviceName, err.Error())`

我暂时加了一个getServiceName方法解决这个问题：
`// getServiceName 获取服务名称
func getServiceName(cfg *conf.Bootstrap, serviceName string) string {
	if cfg == nil {
		return serviceName
	}

	switch localRegistry.Type(cfg.Registry.Type) {
	case localRegistry.Consul:
		return serviceName
	case localRegistry.Nacos:
		return serviceName + ".grpc"
	default:
		return serviceName
	}
}`
